### ISSUE TITLE
Create return object class

### ISSUE THREAD

**Issue by Guptacos** [Guptacos/spotifython#15]
As per issue #7 we have decided to create a return class that is returned by all methods in the api. This should contain internally contents requested from the method, return status, and return message. This allows for cleaner error handling in the client code.

**Comment by spenceryu** [comment]
Note: the status (int) and message (str) error fields are returned in the Spotify web api calls when there is a failure not related to authentication. Authentication errors provide an error (str) and error_description (str) instead.

See [Response Schema](https://developer.spotify.com/documentation/web-api/#response-schema) for more details.
