### ISSUE TITLE
how to handle web API limits

### ISSUE THREAD

**Issue by eyluo** [Guptacos/spotifython#19]
In getting search results, recently played, songs in a playlist, etc., the API provides pagination limits. We decided to get rid of this for 99% of the use cases because we don't want to put the burden of restriction on the user. However, `player.recently_played()` cannot get more than 50. We are considering making the default playback limit 50 (the max), but this is kind of inconsistent with the rest of the API.

**Comment by Guptacos** [comment]
duplicate, see issue #16
