### ISSUE TITLE
Where are enums going to live?

### ISSUE THREAD

**Issue by rmannava** [Guptacos/spotifython#20]
Should they all be in the top level class to reduce information that the client will be forced to remember.

**Comment by Guptacos** [comment]
I agree that they should be in the top level class, especially since that is how they'll be getting instances of each object.

```python
user = sp.get_user(user_id)
user.get_following(sp.ARTIST)
```

**Comment by Guptacos** [comment]
Enums have been moved into a new file, constants.py. This will be imported within __init__.py so that clients can easiliy access the constants
