### ISSUE TITLE
How to deal with functions that can take 1 or more of an obj as an arg?

### ISSUE THREAD

**Issue by Guptacos** [Guptacos/spotifython#21]
Many functions throughout the api can function on 1 object, or multiple instances of the object. For example, to check if a User is following 1 song, vs following 10 songs, you use the same Spotify web endpoint.

We can handle this in one of the following ways:

1. Have two functions, such as `is_following(other) --> bool`, and `is_following_batch([other]) --> [bool]`
2. Have 1 overloaded function `is_following(others) --> [bool]`, where `others` can be a single object, or a list of like objects. Always returns a list of bool with the same number of elements as the input.
3. Same as point 2, however if `objects` is a single object, returns a bool, otherwise a list of bool.

Method 1 makes the most sense in terms of typing; it's always predictable what the input and output should be.

Method 2 makes sense in that the output is always uniform, but can lead to ugly code such as: 
``` python
user = sp.get_user('my_user_id')
track = sp.get_track('Wonderwall')
if user.is_following(track)[0]:
    # do something
```
We would like to avoid users having to arbitrarily index into arrays

This points to method 3 being the cleanest option for client code. However it can lead to confusion and has greater conceptual overhead, so makes me uneasy.

**Comment by spenceryu** [comment]
We are returning multiple possible return types: e.g. if a method returns either str or List[str], we are documenting the return type as Union[Album, List[Album]].
