### ISSUE TITLE
Type hinting enums

### ISSUE THREAD

**Issue by Guptacos** [Guptacos/spotifython#27]
I don't think it's a good idea to type hint enums in the function signatures as strings. That gives insight to the fact that we are setting the enum variables to be strings, whereas they could just as easily be ints or anything else.

Not sure how we should do this.

**Comment by spenceryu** [comment]
We could define a new type (enum package)

**Comment by Guptacos** [comment]
Actual type hinting has been removed. In order to keep classes in separate files and not get circular dependency issues, some imports have to be moved to the bottom of the file. However this means that we can't statically type hint. Instead, input / output types are specified in the function docstring.
