### ISSUE TITLE
Lazy Evaluation

### ISSUE THREAD

**Issue by spenceryu** [Guptacos/spotifython#3]
- Getter methods: check if None -> Make API call if methods are already none.

**Comment by Guptacos** [comment]
Objects should only contain the information available at their creation, and can make additional spotify api requests as necessary when the user tries to access that information

**Comment by Guptacos** [comment]
We need to figure out what information should be cached (if any) and how often it should be updated.

**Comment by rmannava** [comment]
addressed with refresh and update_fields
