### ISSUE TITLE
How to handle errors in the API

### ISSUE THREAD

**Issue by spenceryu** [Guptacos/spotifython#7]
We are wrapping the REST API but hiding the fact that we are using REST API calls from the user. How should failures be handled for the following cases:
- Failure isolation: in the case of lazy loading
- Failure HTTP status codes
- Failure by malformed/unexpected response

**Comment by spenceryu** [comment]
- Distinction between empty objects (your query is bad) vs. some kind of null/error (your token/api call is bad?) to triage where failures are coming from.

**Comment by spenceryu** [comment]
- Try-catch exceptions? How do we wrap the errors to be informative without making ugly code?

**Comment by Guptacos** [comment]
We should discuss this with Josh in office hours on Monday

**Comment by Guptacos** [comment]
As per our discussion with Josh and our group meeting after, we have decided to create a new class "ReturnObject" (naming not decided yet) that contains "contents, returnStatus, returnMsg". Every method in our api will return this object, allowing for users to more cleanly handle errors.
